version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: my-laravel-project
        container_name: my-laravel-project-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - my-laravel-project

    db:
        image: mysql:latest
        container_name: my-laravel-project-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - my-laravel-project

    nginx:
        image: nginx:alpine
        container_name: my-laravel-project-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - my-laravel-project

networks:
    my-laravel-project:
        driver: bridge

volumes:
    dbdata:
